DROP TABLE IF EXISTS USER;
CREATE TABLE USER
(
   ID VARCHAR(50) NOT NULL PRIMARY KEY,
   USERNAME VARCHAR(100) NOT NULL,
   NAME VARCHAR(100) NOT NULL,
   PASSWORD VARCHAR(100) NOT NULL,
   EMAIL VARCHAR(20) NOT NULL,
   PHONE_NO VARCHAR(20) NOT NULL,
   CREATE_TIME TIMESTAMP,
   GENDER CHAR(1),
   ORG_ID VARCHAR(50),
   REMARK VARCHAR(500)
);
DROP TABLE IF EXISTS ORG;
CREATE TABLE ORG
(
   ID VARCHAR(50) NOT NULL PRIMARY KEY,
   NAME VARCHAR(100) NOT NULL,
   CODE VARCHAR(50) NOT NULL,
   CREATE_TIME TIMESTAMP,
   PARENT_ID VARCHAR(50),
   REMARK VARCHAR(500),
   LEAF CHAR(1)
);
DROP TABLE IF EXISTS ROLE;
CREATE TABLE ROLE
(
   ID VARCHAR(50) NOT NULL PRIMARY KEY,
   CREATE_TIME TIMESTAMP,
   NAME VARCHAR(100) NOT NULL,
   REMARK VARCHAR(500)
);
DROP TABLE IF EXISTS USER_ROLE;
CREATE TABLE USER_ROLE
(
   USER_ID VARCHAR(50) NOT NULL,
   ROLE_ID VARCHAR(50) NOT NULL,
   PRIMARY KEY (USER_ID,ROLE_ID)
);
DROP TABLE IF EXISTS FUNCTION;
CREATE TABLE FUNCTION
(
   ID VARCHAR(50) NOT NULL PRIMARY KEY,
   SERVICE_ID VARCHAR(200) NOT NULL,
   CODE VARCHAR(50) NOT NULL,
   NAME VARCHAR(100) NOT NULL,
   TYPE CHAR(1) NOT NULL,
   ACTION VARCHAR(500) DEFAULT NULL,
   REMARK VARCHAR(500) DEFAULT NULL
);

DROP TABLE IF EXISTS ROLE_FUNCTIONS;

CREATE TABLE ROLE_FUNCTIONS(
 ROLE_ID VARCHAR(50),
 FUNCTIONS_ID VARCHAR(50)
);