-- 参数
INSERT INTO CONFIG (ID, APPLICATION, PROFILE, LABEL, NAME, VALUE) VALUES ('r-r.p.d.s.port','reap-rbac','prd','default','server.port','8070');
INSERT INTO CONFIG (ID, APPLICATION, PROFILE, LABEL, NAME, VALUE) VALUES ('r-r.p.d.p.m.salt','reap-rbac','prd','default','password.md5.salt', 'reap');
-- 路由 
INSERT INTO ROUTE VALUES('reap-rbac','reap-rbac','/apis/reap-rbac/**','reap-rbac',null,null);
INSERT INTO ROUTE VALUES('reap-rbac-ui','reap-rbac-ui','/ui/reap-rbac/**','reap-rbac',null,null);
-- 功能码
INSERT INTO FUNCTION (ID,SERVICE_ID,CODE,NAME,TYPE,ACTION) VALUES ('REAPRB0001','reap-rbac','REAPRB0001','机构管理','M','');
INSERT INTO FUNCTION (ID,SERVICE_ID,CODE,NAME,TYPE,ACTION) VALUES ('REAPRB0002','reap-rbac','REAPRB0002','用户管理','M','');
INSERT INTO FUNCTION (ID,SERVICE_ID,CODE,NAME,TYPE,ACTION) VALUES ('REAPRB0003','reap-rbac','REAPRB0003','岗位管理','M','');
INSERT INTO FUNCTION (ID,SERVICE_ID,CODE,NAME,TYPE,ACTION) VALUES ('REAPRB0004','reap-rbac','REAPRB0004','功能码管理','M','');

-- 初始机构及用户

INSERT INTO ORG (ID,NAME,CODE,CREATE_TIME,PARENT_ID,REMARK,LEAF) values ('0001','机构','01',null,null,null,'N');
INSERT INTO USER (ID,USERNAME,NAME,PASSWORD,EMAIL,PHONE_NO,CREATE_TIME,GENDER,ORG_ID,REMARK) VALUES ('0001','admin','管理员','d8721f8bfb91e5c5588bec115aeaf220','admin@reap.org',18603010499, null , 'M','0001', null);
INSERT INTO ROLE (ID,CREATE_TIME,NAME,REMARK) VALUES('0001', NULL, '系统管理岗', NULL);
INSERT INTO USER_ROLE (USER_ID,ROLE_ID) VALUES ('0001','0001');
INSERT INTO ROLE_FUNCTIONS (ROLE_ID, FUNCTIONS_ID) VALUES ('0001', 'REAPRB0003');
INSERT INTO ROLE_FUNCTIONS (ROLE_ID, FUNCTIONS_ID) VALUES ('0001', 'REAPPO0001');
